name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./content/post.md)"
      - uses: infraway/medium-post-markdown@v1.5.0
        with:
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown: ${{ steps.post.outputs.data }}
          app_id: lynnmaxwell0706
          app_secret: lynnmaxwell0706
          base_url: https://medium.com/@lynnmaxwell0706
          post_url: https://medium.com/@lynnmaxwell0706/posts
